#!/command/with-contenv sh
cd /var/www/seismic/backend/ || exit 1

# if ENVIRONMENT="production", then run with gunicorn
if [ "${ENVIRONMENT}" = "production" ]; then
  # https://docs.gunicorn.org/en/latest/design.html#how-many-workers
  WORKERS=${GUNICORN_WORKERS_COUNT:-$(((2 * $(nproc)) + 1))}

  python3 -m gunicorn seismic_site.wsgi \
    --bind "unix:///run/gunicorn.sock" \
    --log-level info \
    --worker-class gevent \
    --workers "${WORKERS}" \
    --bind 0.0.0.0:8000 \
    --timeout 60
else
  python3 manage.py runserver 0.0.0.0:8000
fi
