# Generated by Django 2.2.18 on 2021-03-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200229_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_text',
            field=models.CharField(default='', max_length=300, verbose_name='preview text'),
            preserve_default=False,
        ),
    ]
