# Generated by Django 2.2.10 on 2020-03-02 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200302_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Blog category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category'),
        ),
    ]
