ARG PYTHON_VERSION=3.11.8

FROM python:${PYTHON_VERSION}-slim-bookworm

ENV PYTHONUNBUFFERED=1

ENV ENVIRONMENT ${ENVIRONMENT:-development}
ENV DEBUG ${DEBUG:-True}

ENV RUN_MIGRATIONS=True
ENV RUN_COMPILE_MESSAGES=False
ENV RUN_COLLECT_STATIC=False
ENV RUN_CREATE_SUPER_USER=True

ENV ENABLE_DEBUG_TOOLBAR=True

ENV IS_CONTAINERIZED=True

ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    locales locales-all \
    nginx gcc xz-utils gettext build-essential python3 python3-pip python3-venv python3-dev postgresql-client libpq-dev && \
    apt-get clean


ARG S6_OVERLAY_VERSION=3.1.2.1
ENV S6_CMD_WAIT_FOR_SERVICES_MAXTIME 0

ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz && \
    tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz


COPY docker/nginx/nginx.conf /etc/nginx/sites-available/default
COPY docker/s6-rc.d /etc/s6-overlay/s6-rc.d


# Python virtualenv paths:
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"


# install the backend libraries:
COPY ./api/pyproject.toml ./api/requirements-dev.txt /var/www/seismic/api/
WORKDIR /var/www/seismic/api/
RUN python3 -m pip install --upgrade pip setuptools && \
    python3 -m pip install -r ./requirements-dev.txt

# Copy the back-end source code and install the backend libraries:
COPY ./api/ .

# Make sure scripts in .local are usable:
ENV PATH=/root/.local/bin:$PATH


ENTRYPOINT ["/init"]

EXPOSE 80
