FROM python:3.11.6-slim-bookworm

ENV PYTHONUNBUFFERED=1

ENV ENVIRONMENT ${ENVIRONMENT:-development}
ENV DEBUG ${DEBUG:-True}

ENV RUN_MIGRATION=True
ENV RUN_COMPILE_MESSAGES=False
ENV RUN_COLLECT_STATIC=False
ENV RUN_CREATE_SUPER_USER=True

ENV ENABLE_DEBUG_TOOLBAR=True

ENV IS_CONTAINERIZED=True

ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
    nginx gcc xz-utils gettext build-essential postgresql-client libpq-dev


ARG S6_OVERLAY_VERSION=3.1.2.1
ENV S6_CMD_WAIT_FOR_SERVICES_MAXTIME 0

ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz && \
    tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz


COPY docker/nginx/nginx.conf /etc/nginx/sites-available/default
COPY docker/s6-rc.d /etc/s6-overlay/s6-rc.d


# Python virtualenv paths:
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"


# Copy the back-end source code and install the backend libraries:
WORKDIR /var/www/seismic/api/
COPY ./api/ .
RUN python3 -m pip install --upgrade pip setuptools && \
    python3 -m pip install -r ./requirements-dev.txt


# Make sure scripts in .local are usable:
ENV PATH=/root/.local/bin:$PATH


ENTRYPOINT ["/init"]

EXPOSE 80
