ARG NODE_VERSION=20.11.1

# base image
FROM node:${NODE_VERSION}-bookworm-slim

ARG ENVIRONMENT

ENV ENVIRONMENT ${ENVIRONMENT}
ENV NODE_ENV ${ENVIRONMENT}

# set working directory
WORKDIR /code

# add `/code/node_modules/.bin` to $PATH
ENV PATH /code/node_modules/.bin:${PATH}

# install and cache app dependencies
COPY ./client/package*.json ./
RUN npm i

COPY ./client/docker-entrypoint /
COPY ./client/ /code/

EXPOSE 3000

# start app
CMD ["npm", "start"]
