# Generated by Django 2.2.4 on 2019-09-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0002_auto_20190727_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'Unsuccess'), (0, 'Not tried'), (1, 'Success')], default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='building',
            name='actualizare_pmb',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='adresa',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='an_expertiza',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='arie_desfasurata',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='clasa_categorie',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='building',
            name='editare_admin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='long',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='nr_apart',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='nr_pmb',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='nr_postal',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='building',
            name='nr_sector',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='numar_cadastral',
            field=models.IntegerField(null=True),
        ),
    ]
