# Generated by Django 2.2.4 on 2019-09-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0008_auto_20190917_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='nr_cadastral',
            new_name='numar_cadastral',
        ),
        migrations.RemoveField(
            model_name='building',
            name='an_construire',
        ),
        migrations.AlterField(
            model_name='building',
            name='an_expertiza',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='nr_sector',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='sector',
            field=models.CharField(default='sector', max_length=20),
        ),
    ]
