# Generated by Django 2.2.4 on 2019-10-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('map_app', '0009_auto_20190928_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='an_construire',
            field=models.IntegerField(null=True),
        ),
    ]
