# Generated by Django 2.2.4 on 2019-10-02 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('map_app', '0010_building_status'),
        ('map_app', '0010_building_an_construire'),
    ]

    operations = [
    ]
