# Generated by Django 2.2.7 on 2019-11-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0014_auto_20191113_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='CsvFile',
        ),
    ]
