# Generated by Django 2.2.7 on 2019-11-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('general_id', models.AutoField(primary_key=True, serialize=False)),
                ('risk_category', models.CharField(db_index=True, max_length=50)),
                ('registration_number', models.IntegerField(null=True)),
                ('examination_year', models.IntegerField(null=True)),
                ('certified_expert', models.CharField(max_length=100, null=True)),
                ('observations', models.CharField(max_length=1000, null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('county', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=250, null=True)),
                ('post_code', models.CharField(max_length=250)),
                ('locality', models.CharField(max_length=20)),
                ('year_built', models.IntegerField(null=True)),
                ('height_regime', models.CharField(max_length=50, null=True)),
                ('apartment_count', models.IntegerField(null=True)),
                ('surface', models.FloatField(null=True)),
                ('cadastre_number', models.IntegerField(null=True)),
                ('land_registry_number', models.CharField(max_length=50, null=True)),
                ('administration_update', models.DateField(blank=True, null=True)),
                ('admin_update', models.DateField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Alege'), (1, 'Acceptat'), (-1, 'Respins')], db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('status', models.SmallIntegerField(choices=[(-1, 'Unsuccess'), (0, 'Not tried'), (1, 'Success')], default=0, editable=False)),
            ],
        ),
    ]
