# Generated by Django 2.2.18 on 2021-03-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_auto_20210305_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Not tried'), (1, 'Imported successfully'), (-1, 'Import failed')], default=0, editable=False, verbose_name='status'),
        ),
    ]
