# Generated by Django 3.2.3 on 2021-06-29 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_rename_post_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingProximalUtilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_name_en', models.CharField(default='', max_length=200, unique=True, verbose_name='utility name')),
                ('utility_name_ro', models.CharField(default='', max_length=200, unique=True, verbose_name='denumire utilitate')),
            ],
            options={
                'verbose_name': 'proximal utility',
                'verbose_name_plural': 'proximal utilities',
            },
        ),
        migrations.CreateModel(
            name='BuildingWorkPerformed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name_en', models.CharField(default='', max_length=200, unique=True, verbose_name='work name')),
                ('work_name_ro', models.CharField(default='', max_length=200, unique=True, verbose_name='denumire lucrare')),
            ],
            options={
                'verbose_name': 'work performed',
                'verbose_name_plural': 'works performed',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='apartments_with_6_months_debt',
            field=models.IntegerField(blank=True, null=True, verbose_name='6 month debt apartment count'),
        ),
        migrations.AddField(
            model_name='building',
            name='broken_utilities',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='broken utilities'),
        ),
        migrations.AddField(
            model_name='building',
            name='commercial_space_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='commercial space count'),
        ),
        migrations.AddField(
            model_name='building',
            name='consolidation_status',
            field=models.SmallIntegerField(choices=[(0, 'no'), (1, 'yes, with private funding'), (2, 'yes, with public funding'), (-1, 'demolished')], default=0, verbose_name='is consolidated'),
        ),
        migrations.AddField(
            model_name='building',
            name='disconnected_utilities',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='disconnected utilities'),
        ),
        migrations.AddField(
            model_name='building',
            name='has_owners_association',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='has owners association'),
        ),
        migrations.AddField(
            model_name='building',
            name='is_still_present',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='is standing'),
        ),
        migrations.AddField(
            model_name='building',
            name='office_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='office count'),
        ),
        migrations.AddField(
            model_name='building',
            name='owners_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='owner count'),
        ),
        migrations.AddField(
            model_name='building',
            name='permanently_occupied_apartment_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='permanently inhabited apartment count'),
        ),
        migrations.AddField(
            model_name='building',
            name='proximal_utilities_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='proximal utilities description'),
        ),
        migrations.AddField(
            model_name='building',
            name='public_apartment_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='public apartment count'),
        ),
        migrations.AddField(
            model_name='building',
            name='public_owners',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='public owners'),
        ),
        migrations.AddField(
            model_name='building',
            name='rented_apartment_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='rented apartment count'),
        ),
        migrations.AddField(
            model_name='building',
            name='residents_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='resident count'),
        ),
        migrations.AddField(
            model_name='building',
            name='self_owned_commercial_space_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='self-owned commercial space count'),
        ),
        migrations.AlterField(
            model_name='building',
            name='apartment_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='apartment count'),
        ),
        migrations.AlterField(
            model_name='building',
            name='cadastre_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='cadastre number'),
        ),
        migrations.AlterField(
            model_name='building',
            name='land_registry_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='land registry number'),
        ),
        migrations.AlterField(
            model_name='building',
            name='surface',
            field=models.FloatField(blank=True, null=True, verbose_name='surface'),
        ),
        migrations.CreateModel(
            name='BuildingWorkPerformedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_performed', models.DateField(blank=True, verbose_name='date work performed')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
                ('work_performed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.buildingworkperformed')),
            ],
            options={
                'verbose_name': 'work performed event',
                'verbose_name_plural': 'work performed events',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='proximal_utilities',
            field=models.ManyToManyField(blank=True, to='buildings.BuildingProximalUtilities', verbose_name='proximal utilities'),
        ),
        migrations.AddField(
            model_name='building',
            name='work_performed',
            field=models.ManyToManyField(blank=True, through='buildings.BuildingWorkPerformedEvent', to='buildings.BuildingWorkPerformed', verbose_name='work performed'),
        ),
    ]
