# Generated by Django 3.2.7 on 2021-10-31 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_auto_20210925_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='images_limit',
            field=models.IntegerField(default=3, verbose_name='images limit'),
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('image_type', models.CharField(max_length=255, verbose_name='type')),
                ('compression', models.FloatField(null=True, verbose_name='compression')),
                ('image', models.ImageField(default='Add image file', upload_to='images/')),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (-1, 'Rejected')], db_index=True, default=0, verbose_name='status')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
            ],
        ),
    ]
