# Generated by Django 3.2.7 on 2021-10-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0011_auto_20211031_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='compression',
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='image_type',
            field=models.CharField(choices=[('jpeg', 'JPEG'), ('png', 'PNG')], max_length=255, verbose_name='type'),
        ),
    ]
