# Generated by Django 3.2.7 on 2021-11-09 23:39

import buildings.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0012_auto_20211103_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('image_type', models.CharField(choices=[('jpeg', 'JPEG'), ('png', 'PNG')], max_length=255, verbose_name='type')),
                ('image', models.ImageField(default='Add image file', upload_to='images/')),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (-1, 'Rejected')], db_index=True, default=0, verbose_name='status')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building', validators=[buildings.models.ImageFile.set_images_limit])),
            ],
        ),
    ]
