# Generated by Django 3.2.9 on 2021-11-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0015_alter_imagefile_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='consolidated_buildings',
        ),
    ]
