# Generated by Django 2.2.18 on 2021-02-13 14:30

import buildings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='risk_category',
            field=models.CharField(choices=[('NA', 'N/A'), ('U1', 'U1'), ('U2', 'U2'), ('U3', 'U3'), ('U4', 'U4'), ('RS1', 'RS I'), ('RS2', 'RS II'), ('RS3', 'RS III'), ('RS4', 'RS IV')], db_index=True, default=buildings.models.SeismicCategoryChoice('N/A'), max_length=3, verbose_name='risk category'),
        ),
    ]
