# Generated by Django 3.2.7 on 2021-10-26 08:56

import buildings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_auto_20210925_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='building',
            name='full_name',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='building',
            name='has_warning_panels',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='has warning panels'),
        ),
        migrations.AddField(
            model_name='building',
            name='necessary_support',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='support needed'),
        ),
        migrations.AddField(
            model_name='building',
            name='other_spaces_surface',
            field=models.FloatField(blank=True, null=True, verbose_name='other surface'),
        ),
        migrations.AddField(
            model_name='building',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='building',
            name='type_of_contact',
            field=models.CharField(choices=[('NONE', 'None'), ('OWNER', 'Owner'), ('TENANT', 'Tenant'), ('ADMIN', "Head of the owners' association")], db_index=True, default=buildings.models.ContactChoice['NONE'], max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='building',
            name='surface',
            field=models.FloatField(blank=True, null=True, verbose_name='residential surface'),
        ),
        migrations.AlterField(
            model_name='building',
            name='consolidation_status',
            field=models.CharField(choices=[('NO', 'no'), ('YES_PRIVATE', 'yes, with private funding'), ('YES_PUBLIC', 'yes, with public funding'), ('DEMOLISHED', 'demolished')], db_index=True, default=buildings.models.ConsolidationChoice['NO'], max_length=32, verbose_name='is consolidated'),
        ),
        migrations.AlterField(
            model_name='building',
            name='risk_category',
            field=models.CharField(choices=[('NA', 'N/A'), ('U1', 'U1'), ('U2', 'U2'), ('U3', 'U3'), ('U4', 'U4'), ('RS1', 'RS I'), ('RS2', 'RS II'), ('RS3', 'RS III'), ('RS4', 'RS IV'), ('C', 'Consolidated')], db_index=True, default=buildings.models.SeismicCategoryChoice['NA'], max_length=3, verbose_name='risk category'),
        ),
    ]
