# Generated by Django 3.2.7 on 2021-11-23 19:12

import buildings.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0014_alter_building_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='buildings.building', validators=[buildings.models.ImageFile.check_image_limit]),
        ),
    ]
