# Generated by Django 3.2.10 on 2022-01-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0016_remove_statistic_consolidated_buildings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingproximalutilities',
            old_name='utility_name_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='buildingproximalutilities',
            old_name='utility_name_ro',
            new_name='name_ro',
        ),
        migrations.RenameField(
            model_name='buildingworkperformed',
            old_name='work_name_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='buildingworkperformed',
            old_name='work_name_ro',
            new_name='name_ro',
        ),
    ]
