# Generated by Django 4.2.6 on 2023-10-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildings", "0020_statistic_buildings_per_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statistic",
            name="buildings_per_category",
            field=models.JSONField(
                help_text="The number of buildings per category",
                null=True,
                verbose_name="buildings per category",
            ),
        ),
    ]
