# Generated by Django 2.2.4 on 2019-11-23 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
