# Generated by Django 3.2.7 on 2021-11-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0013_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='locality',
            field=models.CharField(max_length=60, verbose_name='locality'),
        ),
    ]
