# Generated by Django 4.2.6 on 2023-10-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildings", "0019_alter_buildingworkperformed_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statistic",
            name="buildings_per_city",
            field=models.JSONField(
                help_text="The number of buildings per city",
                null=True,
                verbose_name="buildings per city",
            ),
        ),
        migrations.AddField(
            model_name="statistic",
            name="buildings_per_county",
            field=models.JSONField(
                help_text="The number of buildings per county",
                null=True,
                verbose_name="buildings per county",
            ),
        ),
    ]
